services:
  jlr-hu-log-receiver:
    build: .
    container_name: jlr-hu-log-receiver
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./received-logs:/data
    environment:
      PORT: ${PORT:-4318}
      LISTEN_ADDRESS: 192.168.0.3
      LOG_DIRECTORY: /data
